

-- SYSTEM.TARIFFS definition

CREATE TABLE "SYSTEM"."TARIFFS" 
   (	"TARIFF_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50), 
	"MONTHLY_FEE" NUMBER(*,0), 
	"DATA_LIMIT" NUMBER(*,0), 
	"MINUTE_LIMIT" NUMBER(*,0), 
	"SMS_LIMIT" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;




-- SYSTEM.CUSTOMERS definition

CREATE TABLE "SYSTEM"."CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(100), 
	"CITY" VARCHAR2(50), 
	"SIGNUP_DATE" DATE, 
	"NAME" VARCHAR2(50), 
	"TARIFF_ID" NUMBER(*,0), 
	 PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;



-- SYSTEM.MONTHLY_STATS definition

CREATE TABLE "SYSTEM"."MONTHLY_STATS" 
   (	"ID" NUMBER(*,0), 
	"CUSTOMER_ID" NUMBER(*,0), 
	"DATA_USAGE" FLOAT(63), 
	"MINUTE_USAGE" NUMBER(*,0), 
	"SMS_USAGE" NUMBER(*,0), 
	"PAYMENT_STATUS" VARCHAR2(50)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


